spring.application.name=triage

# H2 Duomenu bazes nustatymai (sukuria duomenu baze atmintyje)
spring.datasource.url=jdbc:h2:mem:pulsedeskdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true

# Hugging Face AI API nustatymai
hf.api.url=https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.3
hf.api.token=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